actionbar: "Вы убили %translate-mob% и получили %money% монет"

mobs:
  PIG:
    name: "Свинью"
    min: 0.5
    max: 2
  ZOMBIE:
    name: "Зомби"
    min: 1
    max: 3
  COW:
    name: "корову"
    min: 1
    max: 3